// <auto-generated />
//-----------------------------------------------------------------------
// <copyright file="ResourceKeys.cs" company="Vasont Systems">
//     Copyright (c) Vasont Systems. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
namespace Vasont.Inspire.Core.Properties
{
    /// <summary>
    /// This class is automatically generated and will create resource keys for use within the application.
    /// </summary>
    public static class ResourceKeys
    {
        /// <summary>
        /// Gets the key for the ImageDefaultIcon resource string.
        /// </summary>
        public const string ImageDefaultIcon = "ImageDefaultIcon"; 

        /// <summary>
        /// Gets the key for the VideoDefaultIcon resource string.
        /// </summary>
        public const string VideoDefaultIcon = "VideoDefaultIcon"; 

        /// <summary>
        /// Gets the key for the ArgumentMustBeGreaterThanZeroErrorFormat resource string.
        /// </summary>
        public const string ArgumentMustBeGreaterThanZeroErrorFormat = "ArgumentMustBeGreaterThanZeroErrorFormat"; 

        /// <summary>
        /// Gets the key for the DeserializeFileNotFoundErrorText resource string.
        /// </summary>
        public const string DeserializeFileNotFoundErrorText = "DeserializeFileNotFoundErrorText"; 

        /// <summary>
        /// Gets the key for the InvalidFileArgumentErrorText resource string.
        /// </summary>
        public const string InvalidFileArgumentErrorText = "InvalidFileArgumentErrorText"; 
    }
}
