//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vasont.Inspire.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vasont.Inspire.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than 0..
        /// </summary>
        public static string ArgumentMustBeGreaterThanZeroErrorFormat {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanZeroErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified was not found..
        /// </summary>
        public static string DeserializeFileNotFoundErrorText {
            get {
                return ResourceManager.GetString("DeserializeFileNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageDefaultIcon {
            get {
                object obj = ResourceManager.GetObject("ImageDefaultIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid file path must be specified..
        /// </summary>
        public static string InvalidFileArgumentErrorText {
            get {
                return ResourceManager.GetString("InvalidFileArgumentErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string LabelAndText {
            get {
                return ResourceManager.GetString("LabelAndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string LabelApplicationText {
            get {
                return ResourceManager.GetString("LabelApplicationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Vendor.
        /// </summary>
        public static string LabelAtVendorText {
            get {
                return ResourceManager.GetString("LabelAtVendorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string LabelCancelledText {
            get {
                return ResourceManager.GetString("LabelCancelledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string LabelCompletedText {
            get {
                return ResourceManager.GetString("LabelCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string LabelContainsText {
            get {
                return ResourceManager.GetString("LabelContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string LabelDebugText {
            get {
                return ResourceManager.GetString("LabelDebugText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not Contain.
        /// </summary>
        public static string LabelDoesNotContainText {
            get {
                return ResourceManager.GetString("LabelDoesNotContainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not End With.
        /// </summary>
        public static string LabelDoesNotEndWithText {
            get {
                return ResourceManager.GetString("LabelDoesNotEndWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Not Start With.
        /// </summary>
        public static string LabelDoesNotStartWithText {
            get {
                return ResourceManager.GetString("LabelDoesNotStartWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends With.
        /// </summary>
        public static string LabelEndsWithText {
            get {
                return ResourceManager.GetString("LabelEndsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LabelErrorText {
            get {
                return ResourceManager.GetString("LabelErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        public static string LabelExportingText {
            get {
                return ResourceManager.GetString("LabelExportingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Retrieving.
        /// </summary>
        public static string LabelFailedRetrievingText {
            get {
                return ResourceManager.GetString("LabelFailedRetrievingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Sending.
        /// </summary>
        public static string LabelFailedSendingText {
            get {
                return ResourceManager.GetString("LabelFailedSendingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        public static string LabelFatalText {
            get {
                return ResourceManager.GetString("LabelFatalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string LabelGeneralText {
            get {
                return ResourceManager.GetString("LabelGeneralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string LabelInformationText {
            get {
                return ResourceManager.GetString("LabelInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string LabelNoText {
            get {
                return ResourceManager.GetString("LabelNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string LabelOrText {
            get {
                return ResourceManager.GetString("LabelOrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string LabelSecurityText {
            get {
                return ResourceManager.GetString("LabelSecurityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts With.
        /// </summary>
        public static string LabelStartsWithText {
            get {
                return ResourceManager.GetString("LabelStartsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string LabelSystemText {
            get {
                return ResourceManager.GetString("LabelSystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating.
        /// </summary>
        public static string LabelTranslatingText {
            get {
                return ResourceManager.GetString("LabelTranslatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LabelWarningText {
            get {
                return ResourceManager.GetString("LabelWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string LabelYesText {
            get {
                return ResourceManager.GetString("LabelYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked by.
        /// </summary>
        public static string LockedByText {
            get {
                return ResourceManager.GetString("LockedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked for Editing by.
        /// </summary>
        public static string LockedForEditingByText {
            get {
                return ResourceManager.GetString("LockedForEditingByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked for review by.
        /// </summary>
        public static string LockedForReviewByText {
            get {
                return ResourceManager.GetString("LockedForReviewByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked for translation by.
        /// </summary>
        public static string LockedForTranslationByText {
            get {
                return ResourceManager.GetString("LockedForTranslationByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Days, {1} Hours, {2} Minutes, {3} Seconds.
        /// </summary>
        public static string RuntimeMessageText {
            get {
                return ResourceManager.GetString("RuntimeMessageText", resourceCulture);
            }
        }
    }
}
